version: "3.8"
services:
  dev: &default
    build:
      context: .
      target: dev
    volumes:
      - ./:/work
    depends_on:
      - "localstack"
      - "mockserver"
  dev:
    <<: *default
    command: tail -f /dev/null
  test:
    <<: *default
    command: bash -c "cd /work && pytest --cov link.aggregator --cov-report html -x tests"
    profiles:
      - test
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - "4566:4566"
  mockserver:
    image: mockserver/mockserver
    ports:
      - "1080:1080"