version: "3.8"
services:
  aggregator:
    image: mcai4gl2/link-aggregator
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - FROM_WHITE_LIST=${FROM_WHITE_LIST}
      - GITHUB_AUTH_TOKEN=${GITHUB_AUTH_TOKEN}
    depends_on:
      - "selenium"
  selenium:
    image: selenium/standalone-chrome:4.1.4-20220427
    ports:
      - "4444:4444"
    shm_size: '2g'
