name: Run link aggregator
on:
  workflow_dispatch:
    inputs:
      something:
        description: 'Not really reaquired but I think there has to be a parameter'
        required: false
  schedule:
    - cron: '*/15 * * * *'
jobs:
  build:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: aggregator
        run: "docker run --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --env AWS_DEFAULT_REGION=us-east-1 --env AWS_BUCKET_NAME=links-email --env FROM_WHITE_LIST='Geng Li' --env GITHUB_AUTH_TOKEN=${{ secrets.AUTH_TOKEN }} mcai4gl2/link-aggregator"
